### PR TITLE
Make formatCaseClass return an OFormat

### PR DESCRIPTION
**Pull request by clamothe**
```
trait Format[A] extends Writes[A] with Reads[A]
trait OFormat[A] extends OWrites[A] with Reads[A] with Format[A]

trait OWrites[-A] extends Writes[A] {
  def writes(o: A): JsObject
  ...
}
```

formatCaseClass currently creates a Format with a [writes method that always returns a JsObject](https://github.com/xdotai/play-json-extensions/blob/984d9d418ddafa52bc2a930d2627cdd16ebfc516/src/main/scala/play-json.scala#L336). By switching Format to OFormat here, callers of this method have a type-safe guarantee that it's write method returns a JsObject.

At a cursory glance, I didn't identify any other formatters that always write JsObjects.

For more info on OFormat vs Format, this is helpful: https://stackoverflow.com/a/32290351

### CODE REVIEW

**Comment by cvogt** [comment]
@clamothe I suggest you add the email address you used in your commit to your github account, so commits are linked properly

**Comment by clamothe** [comment]
Done

**Comment by cvogt** [comment]
thx  :)!! I am working through a little issue with the github support adding a CLA here (just saying I agree to Apache 2.0 licensing), as I was advised to do by someone who knows FOSS better than I do. But then I'll get 0.9.0 out.

**Comment by clamothe** [comment]
Great, thank you. Have you had a chance to look at PR #36 as well?

**Comment by cvogt** [comment]
update: still waiting to resolve the issue: https://github.com/cla-assistant/cla-assistant/issues/130

hopefully soon

**Comment by cvogt** [comment]
@clamothe ok, finally figured that out. You mind signing the CLA (it just say you agree with Apache 2.0), by clicking on https://cla-assistant.io/xdotai/play-json-extensions?pullRequest=35 ?

**Comment by clamothe** [comment]
Done

**Comment by clamothe** [comment]
I'm eager to use this feature as well as #36. If both seem like appropriate additions, let me know if you need anything else from my end to make it happen. Thanks

**Comment by cvogt** [comment]
will publish tomorrow. merged everything

**Comment by clamothe** [comment]
Thank you!

**Comment by cvogt** [comment]
released 2.11 to sonatype a few hours ago, will take up to a day to arrive in maven central

**Comment by clamothe** [comment]
Thank you

**Pull request merged**
