### PR TITLE
Support for snake_case

### PR DESCRIPTION
**Pull request by mtsokol**

### CODE REVIEW

**Comment by jcurr** [comment]
@mtsokol I would like to use your changes, would you be willing to sign the agreement so that the branch can be merged? Thanks

**Comment by mtsokol** [comment]
@jcurr sure, I've just signed it.

**Comment by rucas** [comment]
bump. would like to use this feature.

**Comment by henricook** [comment]
@mtsokol Next time it'd be really useful to update the README - especially for a breaking change like this.

To retain old behaviour should we be using `implicit val encoder: NameEncoder = BaseNameEncoder()`? Like this:

```scala
implicit val format: Format[MyCaseClass] = {
    implicit val encoder: NameEncoder = BaseNameEncoder()
    Jsonx.formatCaseClass[MyCaseClass]
  }
```

**Pull request merged**
